services:
  java-app:
    image: java-image:v1
    container_name: java-app
    depends_on:
      - postgres-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/netflixclonedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - mynetwork

  node-server:
    image: node-image:v1
    container_name: node-server
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  client:
    image: client:v1
    container_name: client
    depends_on:
      - java-app
      - node-server
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://java-app:8080
      - REACT_APP_NODE_URL=http://node-server:3001
    networks:
      - mynetwork